### ISSUE TITLE
Import configuration from a file

### ISSUE THREAD

**Issue by ethmtrgt** [Rs-py/RedditBot#4]
Hello, thank you for the good work, the bot looks helpful. I have an idea to make it more practical by importing settings from a configuration file. I would like to work on this if you can assign me. Thanks :)

**Comment by Rs-py** [comment]
That’s a great idea! Can’t wait to see what you come up with! @ethmtrgt

**Comment by ethmtrgt** [comment]
Thank you for the merge! We can close this issue :)
